import pandas as pd

# Data provided as a list of lists
data = [
    ["AB", "Aberdeen", "", "33 (Highest number 56)"],
    ["AL", "St Albans", "", "10"],
    ["B", "Birmingham", "", "79 (Highest number 98)"],
    ["BA", "Bath", "", "19 (Highest number 22)"],
    ["BB", "Blackburn", "", "13 (Highest number 18)"],
    ["BD", "Bradford", "", "27 (Highest number 99)"],
    ["BH", "Bournemouth", "", "26 (Highest number 31)"],
    ["BL", "Bolton", "", "10 (Highest number 9)"],
    ["BN", "Brighton", "", "30 (Highest number 45)"],
    ["BR", "Bromley", "", "8"],
    ["BS", "Bristol", "", "37 (Highest number 49)"],
    ["BT", "Belfast", "", "81 (Highest number 94)"],
    ["CA", "Carlisle", "", "28"],
    ["CB", "Cambridge", "", "16 (Highest number 25)"],
    ["CF", "Cardiff", "", "35 (Highest number 83)"],
    ["CH", "Chester", "", "37 (Highest number 66)"],
    ["CM", "Chelmsford", "", "25 (Highest number 77)"],
    ["CO", "Colchester", "", "16"],
    ["CR", "Croydon", "", "9 (Highest number 8)"],
    ["CT", "Canterbury", "", "21"],
    ["CV", "Coventry", "Coventry", "24 (Highest number 47)"],
    ["CW", "Crewe", "", "12"],
    ["DA", "Dartford", "", "18"],
    ["DD", "Dundee", "", "11"],
    ["DE", "Derby", "", "23 (Highest number 75)"],
    ["DG", "Dumfries", "Dumfries and Galloway", "15 (Highest number 16)"],
    ["DH", "Durham", "", "9"],
    ["DL", "Darlington", "", "17"],
    ["DN", "Doncaster", "", "32 (Highest number 41)"],
    ["DT", "Dorchester", "", "11"],
    ["DY", "Dudley", "", "14"],
    ["E", "East London", "", "20 (Includes E1W)"],
    ["EC", "East Central London", "", "23 (EC is split into four, with EC1, EC2 and EC4 split -A, -M, -N, -R, -V & -Y and EC3 split -A, -M, -N, -R & -V; highest number 4/4Y)"],
    ["EH", "Edinburgh", "", "54 (Highest number 55)"],
    ["EN", "Enfield", "", "11"],
    ["EX", "Exeter", "", "33 (Highest number 39)"],
    ["FK", "Falkirk", "", "21"],
    ["FY", "Blackpool", "The Fylde", "8"],
    ["G", "Glasgow", "", "52 (Highest number 84)"],
    ["GL", "Gloucester", "", "27 (Highest number 56)"],
    ["GU", "Guildford", "", "38 (Highest number 52)"],
    ["HA", "Harrow", "Harrow", "10 (Highest number 9)"],
    ["HD", "Huddersfield", "", "9"],
    ["HG", "Harrogate", "", "5"],
    ["HP", "Hemel Hempstead", "", "24 (Highest number 27)"],
    ["HR", "Hereford", "", "9"],
    ["HS", "Hebrides", "", "9"],
    ["HU", "Hull", "", "20"],
    ["HX", "Halifax", "", "7"],
    ["IG", "Ilford", "Possibly Ilford and Gants Hill (or Barking)", "11"],
    ["IP", "Ipswich", "", "33"],
    ["IV", "Inverness", "", "52 (Highest number 63)"],
    ["KA", "Kilmarnock", "Possibly Kilmarnock and Ayr or Kilmarnock", "30"],
    ["KT", "Kingston upon Thames", "", "24"],
    ["KW", "Kirkwall", "", "16 (Highest number 17)"],
    ["KY", "Kirkcaldy", "", "16"],
    ["L", "Liverpool", "", "40"],
    ["LA", "Lancaster", "", "23"],
    ["LD", "Llandrindod Wells", "", "8"],
    ["LE", "Leicester", "", "21 (Highest number 67)"],
    ["LL", "Llandudno", "", "67 (Highest number 78)"],
    ["LN", "Lincoln", "", "13"],
    ["LS", "Leeds", "Leeds", "29"],
    ["LU", "Luton", "", "7"],
    ["M", "Manchester", "", "43 (Highest number 90)"],
    ["ME", "Rochester", "Medway", "20"],
    ["MK", "Milton Keynes", "", "26 (Highest number 46)"],
    ["ML", "Motherwell", "", "12"],
    ["N", "North London", "", "23 (Includes N1C, Highest number 22)"],
    ["NE", "Newcastle upon Tyne", "", "61 (Highest number 71)"],
    ["NG", "Nottingham", "", "29 (Highest number 34)"],
    ["NN", "Northampton", "", "19 (Highest number 29)"],
    ["NP", "Newport", "", "18 (Highest number 44)"],
    ["NR", "Norwich", "", "35"],
    ["NW", "North West London", "", "11"],
    ["OL", "Oldham", "", "16"],
    ["OX", "Oxford", "Oxford", "27 (Highest number 49)"],
    ["PA", "Paisley", "", "67 (Highest number 80)"],
    ["PE", "Peterborough", "", "38"],
    ["PH", "Perth", "", "43 (Highest number 50)"],
    ["PL", "Plymouth", "", "35"],
    ["PO", "Portsmouth", "Portsmouth", "34 (Highest number 41)"],
    ["PR", "Preston", "", "11 (Highest number 26)"],
    ["RG", "Reading", "", "30 (Highest number 45)"],
    ["RH", "Redhill", "", "20"],
    ["RM", "Romford", "", "20"],
    ["S", "Sheffield", "", "45 (Highest number 81)"],
    ["SA", "Swansea", "", "51 (Highest number 73)"],
    ["SE", "South East London", "", "28"],
    ["SG", "Stevenage", "", "19"],
    ["SK", "Stockport", "", "19 (Highest number 23)"],
    ["SL", "Slough", "Slough", "10 (Highest number 9)"],
    ["SM", "Sutton", "Possibly Sutton and Morden, the two post towns that are within the SM area", "7"],
    ["SN", "Swindon", "", "18 (Highest number 26)"],
    ["SO", "Southampton", "", "23 (Highest number 53)"],
    ["SP", "Salisbury", "Salisbury Plain", "11"],
    ["SR", "Sunderland", "", "8"],
    ["SS", "Southend-on-Sea", "Southend-on-Sea", "17"],
    ["ST", "Stoke-on-Trent", "Stoke-on-Trent", "21"],
    ["SW", "South West London", "", "27 (SW1 is split into eight, -A, -E, -H, -P, -V, -W, -X & -Y; highest number 20)"],
    ["SY", "Shrewsbury", "", "25"],
    ["TA", "Taunton", "", "24"],
    ["TD", "Galashiels", "Tweeddale", "15"],
    ["TF", "Telford", "", "13"],
    ["TN", "Tunbridge Wells", "", "40"],
    ["TQ", "Torquay", "", "14"],
    ["TR", "Truro", "", "27"],
    ["TS", "Cleveland", "Teesside", "29"],
    ["TW", "Twickenham", "", "20"],
    ["UB", "Southall", "Uxbridge", "11"],
    ["W", "West London", "", "26 (W1 is split into thirteen, -A to -D, -F to -H, -J, -K, -S to -U & -W; highest number 14)"],
    ["WA", "Warrington", "", "16"],
    ["WC", "West Central London", "", "14 (WC1 is split into eight, -A, -B, -E, -H, -N, -R, -V & -X; WC2 is split into six, -A, -B, -E, -H, -N & -R; highest number 2R)"],
    ["WD", "Watford", "Watford", "11 (Highest number 25)"],
    ["WF", "Wakefield", "", "17"],
    ["WN", "Wigan", "", "8"],
    ["WR", "Worcester", "", "15"],
    ["WS", "Walsall", "", "15"],
    ["WV", "Wolverhampton", "", "16"],
    ["YO", "York", "", "29 (Highest number 47)"],
    ["ZE", "Lerwick", "Zetland", "3"]
]

# Create a DataFrame
columns = ["Postcode_Area", "Primary_Area", "Extra_Info", "Details"]
df = pd.DataFrame(data, columns=columns)

# Save to CSV
df.to_csv("postcode_areas.csv", index=False)

print("Dataset saved as 'postcode_areas.csv'.")
